### ISSUE TITLE
InvalidCastException thrown when using InjectValidator() after RuleForEach()

### ISSUE THREAD

**Issue by poneymusical** [JeremySkinner/FluentValidation#1076]
### System Details

- FluentValidation version: 8.2.0
- Web Framework version : ASP.NET Core 2.1

### Issue Description
Hello,

I encounter an InvalidCastException whenever I try to use a statement like : `RuleForEach(x_ => x_.Children).InjectValidator();` in a validator implementation. 

I cannot send the original project, but I made a toy project which replicates the issue. The case is simple: I have a Parent class with a list of Children. I have validators implemented for both classes. Everything is registered in the service container using AddFluentValidation with following parameters : 
`fv.RegisterValidatorsFromAssemblyContaining<ParentValidator>();
 fv.RunDefaultMvcValidationAfterFluentValidationExecutes = false;`

Here's the zip archive with the toy project, also the postman query
[WebApplication1.zip](https://github.com/JeremySkinner/FluentValidation/files/3043446/WebApplication1.zip)
  
Am I doing something wrong? I know I could use the `SetValidator(new ChildValidator())` to circumvent the issue but I'd like not to instantiate the ChildValidator directly.

Exception message: 
System.InvalidCastException: Unable to cast object of type 'FluentValidation.ValidationContext' to type 'FluentValidation.ValidationContext`1[WebApplication1.Models.Parent]'.

Thanks in advance for your help!
Regards,
Guillaume.

**Comment by JeremySkinner** [comment]
Hi, please could you post the full stacktrace? Thanks

**Comment by poneymusical** [comment]
Hello,

Here it is:

System.InvalidCastException: Unable to cast object of type 'FluentValidation.ValidationContext' to type 'FluentValidation.ValidationContext`1[WebApplication1.Models.Parent]'.
   at FluentValidation.DependencyInjectionExtensions.<>c__DisplayClass3_0`2.<InjectValidator>b__0(IValidationContext context) in C:\Projects\FluentValidation\src\FluentValidation.DependencyInjectionExtensions\DependencyInjectionExtensions.cs:line 93
   at FluentValidation.Validators.ChildValidatorAdaptor.Validate(PropertyValidatorContext context) in C:\Projects\FluentValidation\src\FluentValidation\Validators\ChildValidatorAdaptor.cs:line 45
   at FluentValidation.Internal.CollectionPropertyRule`1.InvokePropertyValidator(ValidationContext context, IPropertyValidator validator, String propertyName) in C:\Projects\FluentValidation\src\FluentValidation\Internal\CollectionPropertyRule.cs:line 187
   at FluentValidation.Internal.PropertyRule.Validate(ValidationContext context)+MoveNext() in C:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 292
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in C:\Projects\FluentValidation\src\FluentValidation\AbstractValidator.cs:line 115
   at FluentValidation.AspNetCore.FluentValidationModelValidator.Validate(ModelValidationContext mvContext) in C:\Projects\FluentValidation\src\FluentValidation.AspNetCore\FluentValidationModelValidatorProvider.cs:line 88
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.ValidateNode()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Validate(ModelMetadata metadata, String key, Object model, Boolean alwaysValidateAtTopLevel)
   at FluentValidation.AspNetCore.FluentValidationVisitor.Validate(ModelMetadata metadata, String key, Object model, Boolean alwaysValidateAtTopLevel) in C:\Projects\FluentValidation\src\FluentValidation.AspNetCore\FluentValidationVisitor.cs:line 40
   at Microsoft.AspNetCore.Mvc.ModelBinding.ObjectModelValidator.Validate(ActionContext actionContext, ValidationStateDictionary validationState, String prefix, Object model, ModelMetadata metadata)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.EnforceBindRequiredAndValidate(ObjectModelValidator baseObjectValidator, ActionContext actionContext, ParameterDescriptor parameter, ModelMetadata metadata, ModelBindingContext modelBindingContext, ModelBindingResult modelBindingResult)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by JeremySkinner** [comment]
Thanks. Looks like it's a bug specific to when `InjectValidator` is used in comination with `RuleForEach` (this dosn't happen with `RuleFor`.) Fix should be fairly straightforward - I'll try and get this done and released within the next couple of days.

**Comment by poneymusical** [comment]
All right, thanks a lot for your help! I'll use the SetValidator method while waiting for the fix.

**Comment by JeremySkinner** [comment]
I've pushed out 8.2.1 with this change. It appear on nuget shortly.
