### ISSUE TITLE
DTO validation with FluentValidation fails

### ISSUE THREAD

**Issue by grinay** [JeremySkinner/FluentValidation#1213]
### System Details

- FluentValidation version: 8.4.0
- Web Framework version: ASP.NET Core 2.2

### Issue Description
I face into an issue with using FluentValidation. I'm trying to validate DTO. In my DTO property look like this

```
[Required]
public List<InvoiceLineCreateOrUpdateInput> Lines { get; set; }
and then my rule
```

`  RuleFor(x => x.Lines).NotNull().WithMessage("Lines can't be empty");`
If I pass my json object(DTO)

```
{ 
"Prop1":"value"
"lines":[myarray here] 
}
```
into API with "lines" propery, everything works fine. But if the user forgot to put "lines" property into the object

```
{ 
"Prop1":"value"
//missing
}
```
I've got ane exception

System.ArgumentNullException: Value cannot be null.
Parameter name: source
The fluent validation registered with the standard provided way as

```
.AddFluentValidation(fv =>
                {
                    fv.RegisterValidatorsFromAssembly(typeof(AutofacApplicationModule).Assembly);
                })
```
If I don't use fluent validation standard DataAnotation will return validation error "The Lines field is required."

But in case of when we enable fluent validation, it just fails internally.

I think that the order of validation pipeline can solve it to move fluent validation to the end of pipe like that:

```
        .AddMvcOptions(options =>
        {
            var fvProvider = options.ModelValidatorProviders[0];
            options.ModelValidatorProviders.RemoveAt(0);
            options.ModelValidatorProviders.Add(fvProvider);
        });
```
But it doesn't help. I've got the same exception. How to overcome this? How to make DataAnattation validator works.

**Comment by JeremySkinner** [comment]
The order of the providers is correct - FluentValidation should run first. 

Please post the full stack trace.

**Comment by grinay** [comment]
**LIne 15 in this rule if "   .Must(x => x.Any()).WithMessage("At least one invoice position is required")"**

```            RuleFor(x => x.Lines).NotNull().WithMessage("Lines can't be empty")
                .Must(x => x.Any()).WithMessage("At least one invoice position is required")
                .ForEach(invoiceLineRule =>
                    invoiceLineRule.Must(x => !x.ProductId.HasValue && !x.PlanExternalId.HasValue)
                        .WithMessage("Either product or plan is required")
                )
                .ForEach(invoiceLineRule =>
                    invoiceLineRule.Must(line =>
                            line.TotalPrice == Math.Round(line.Quantity * line.UnitPrice, 2, MidpointRounding.AwayFromZero) //TODO Move to core, BusinessRule
                    ).WithMessage("Line total amount is not valid")
                );
```

```
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Foys.FinancialDashboard.Application.Invoices.Validators.InvoiceCreateValidator.<>c.<.ctor>b__0_1(List`1 x) in /Users/grinay/Downloads/meer-invoicing/src/Foys.FinancialDashboard.Application/Invoices/Validators/InvoiceValidators.cs:line 15
   at FluentValidation.Validators.PredicateValidator.IsValid(PropertyValidatorContext context) in /home/jskinner/code/FluentValidation/src/FluentValidation/Validators/PredicateValidator.cs:line 34
   at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context) in /home/jskinner/code/FluentValidation/src/FluentValidation/Validators/PropertyValidator.cs:line 55
   at FluentValidation.Internal.PropertyRule.Validate(ValidationContext context)+MoveNext() in /home/jskinner/code/FluentValidation/src/FluentValidation/Internal/PropertyRule.cs:line 282
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in /home/jskinner/code/FluentValidation/src/FluentValidation/AbstractValidator.cs:line 115
   at FluentValidation.AspNetCore.FluentValidationModelValidator.Validate(ModelValidationContext mvContext) in /home/jskinner/code/FluentValidation/src/FluentValidation.AspNetCore/FluentValidationModelValidatorProvider.cs:line 91
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.ValidateNode()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Validate(ModelMetadata metadata, String key, Object model, Boolean alwaysValidateAtTopLevel)
   at FluentValidation.AspNetCore.FluentValidationVisitor.Validate(ModelMetadata metadata, String key, Object model, Boolean alwaysValidateAtTopLevel) in /home/jskinner/code/FluentValidation/src/FluentValidation.AspNetCore/FluentValidationVisitor.cs:line 40
   at Microsoft.AspNetCore.Mvc.ModelBinding.ObjectModelValidator.Validate(ActionContext actionContext, ValidationStateDictionary validationState, String prefix, Object model, ModelMetadata metadata)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.EnforceBindRequiredAndValidate(ObjectModelValidator baseObjectValidator, ActionContext actionContext, ParameterDescriptor parameter, ModelMetadata metadata, ModelBindingContext modelBindingContext, ModelBindingResult modelBindingResult)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[20:04:40 INF] Request finished in 5458.8025ms 500 
```

**Comment by JeremySkinner** [comment]
Well yes, that will throw an argument null exception if the property is missing. 

You’re calling `x.Any()`. If x is null then you’ll get an exception - that’s nothing to do with FluentValidation, this is still c# you’re using and `Any` can’t be passed null.

You still need to provide a null check like you would with any other c# code.  You can do this on the rule with a separate `When` condition, or directly inside the call to `Must`.

**Comment by grinay** [comment]
Wait, but what about first rule in chain? RuleFor(x => x.Lines).NotNull().WithMessage("Lines can't be empty"). What exactly it is doing?  Shouldn't it fail the chain before "Must" action?

**Comment by JeremySkinner** [comment]
By default rules are executed independently and in isolation. You can change that behaviour for rules in the same chain if you want by setting the cascade mode: https://fluentvalidation.net/start#setting-the-cascade-mode

**Comment by grinay** [comment]
CascadeMode = CascadeMode.StopOnFirstFailure; helps.  Thanks. 
But I'm curious. 
Is there a way to use standard DataAnnotation provider and in case it fails just return its errors before fluent validation called?

**Comment by JeremySkinner** [comment]
No. You’d need to write something custom if you wanted to do that.

**Comment by grinay** [comment]
Thanks.
