### ISSUE TITLE
ShouldHaveValidationErrorFor throws NullReferenceException

### ISSUE THREAD

**Issue by eloisetaylor5693** [JeremySkinner/FluentValidation#1232]
#978 # System Details

**FluentValidation version:**  8.4.0
**Framework version:** .net standard 2.0.3

### Issue Description
This throws a NullReferenceException: 

```C#
private MyNewValidator Validator { get; }
            
[Test]           
public void ThenThereIsAnErrorMessageForProperty_Take()            
{             
	Validator.ShouldHaveValidationErrorFor(x => x.Take, -25, "*");         
}
```

**Stack trace:**
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at FluentValidation.DefaultValidatorExtensions.Validate[T](IValidator`1 validator, T instance, IValidatorSelector selector, String ruleSet)
   at FluentValidation.TestHelper.ValidationTestExtension.TestValidate[T,TValue](IValidator`1 validator, Expression`1 expression, T instanceToValidate, TValue value, String ruleSet, Boolean setProperty)
   at FluentValidation.TestHelper.ValidationTestExtension.ShouldHaveValidationErrorFor[T,TValue](IValidator`1 validator, Expression`1 expression, TValue value, String ruleSet)
```

**Comment by JeremySkinner** [comment]
Hi, yes you need to instantiate the validator first and assign it to your property. By default it’ll be null.

**Comment by eloisetaylor5693** [comment]
I did miss a bit out of the snippet... there is a constructor.... but I was being a wally and forgot to instantiate the validator.  Thanks :)
