### ISSUE TITLE
Issue while using Localization (IStringLocalizer)

### ISSUE THREAD

**Issue by Sandeep321** [JeremySkinner/FluentValidation#1255]
### System Details

FluentValidation version: 8.1.3
Web Framework version (ASP.NET Core 2.2):

### Issue Description
While using the IStringLocalizer, I can see that requests to get the message from the localizer get fired irrespective of whether the validation has failed or passed. I was assuming it will request the message only when it fails.

We are using a localization framework where it gets localized strings from JSON files. I would not want to make a call to the localizer in case my validation has passed as it is of no use.

`public class PersonValidator : AbstractValidator<Person> {
  public PersonValidator(IStringLocalizer<Person> localizer) {
    RuleFoR(x => x.Surname).NotNull().WithMessage(x => localizer["Key"]);
  }
}`

Here the localizer is a dependency that reads a no of JSON files for the given key and returns the value. For validation on a huge data, it makes it slow.

**Comment by JeremySkinner** [comment]
Hi, typically the error message callback is only invoked if validation fails. But in an MVC project with client-side validation enabled the error message also has to be extracted to pre-load the client-side messages. If you don’t want this to happen then you should disable client-size validation.

**Comment by Sandeep321** [comment]
@JeremySkinner We are using a .Net core API and we won't need MVC client-side validation.
However, I did try to disable client-side validation but it still behaves the same.
Below is my AddMvc to services.

`            services
                .AddMvc().AddViewOptions(options =>
                    options.HtmlHelperOptions.ClientValidationEnabled = false)
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
                .AddFluentValidation(fv =>
                    fv.RegisterValidatorsFromAssemblyContaining<Startup>());`

**Comment by JeremySkinner** [comment]
If you're not using clientside validation then it's probably not that that's causing it. Just to be on the safe side try disabling in the call to AddFluentValidaition too:

```
.AddFluentValidation(fv => { 
  fv.RegisterValidatorsFromAssemblyContaining<Startup>();
  fv.fv.ConfigureClientsideValidation(enabled:false);
});
```

If you're still seeing the same issue then put a breakpoint inside the `WithMessage` callback or inside your custom StringLocalizer and retrieve the stack trace, which will show you where it's being called.

**Comment by Sandeep321** [comment]
Tried disabling in the call to AddFluentValidaition too but the issue still persists. Will update here when I find something after further investigation.

**Comment by Sandeep321** [comment]
@JeremySkinner 
It looks like an issue with FluentValidator. I have created a working sample which is available at https://github.com/Sandeep321/FluentValidationExample.
It's a very simple project where I tried to replicate the issue. I tried the methods as suggested by you but still, it invokes the localizer method every time irrespective of whether the validation has failed or passed.

Repro steps:
1. Clone the repo mentioned above.
2. Run the API, it should open "https://localhost:44363/swagger/index.html" by default.
3. Execute POST - /api/Values/Test with default values in body as: {  "id": 0,  "name": "string"}
4. In response, you shall see only one element in errors collection as  - Student Id should be greater than 100 (Response is as expected as only one rule is failed)
5. However, if you put debugger inside Localizer.GetLocalizedString(string message), you will see that it gets invoked for both the rules defined under StudentViewModelValidator. Although only one rule has failed.

I have tried different options to disable client-side validation. You can check those Options as Option 1, Option 2 and Option 3 inside Startup file.

Waiting to hear from you.

**Comment by JeremySkinner** [comment]
Did you retrieve a stack trace as I suggested? Please post that here as a first step as it will be significantly quicker to diagnose than digging through a sample project.

**Comment by Sandeep321** [comment]
Not sure which stack trace you are referring to. If you are asking of output from debug window, here it is:

Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/2.0 POST https://localhost:44363/api/Values/Test application/json-patch+json 33
Microsoft.AspNetCore.Routing.EndpointMiddleware:Information: Executing endpoint 'FluentValidationExample.Controllers.ValuesController.Post (FluentValidationExample)'
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Route matched with {action = "Post", controller = "Values"}. Executing action FluentValidationExample.Controllers.ValuesController.Post (FluentValidationExample)
Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor:Information: Executing ObjectResult, writing value of type 'Microsoft.AspNetCore.Mvc.ValidationProblemDetails'.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action FluentValidationExample.Controllers.ValuesController.Post (FluentValidationExample) in 3447.6821ms
Microsoft.AspNetCore.Routing.EndpointMiddleware:Information: Executed endpoint 'FluentValidationExample.Controllers.ValuesController.Post (FluentValidationExample)'
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 3462.7004ms 400 application/problem+json; charset=utf-8

**Comment by Sandeep321** [comment]
Please have a look at :

at FluentValidationExample.Validators.StudentViewModelValidator..ctor(ILocalizer localizer)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at FluentValidation.AspNetCore.ServiceProviderValidatorFactory.CreateInstance(Type validatorType)
   at FluentValidation.AspNetCore.FluentValidationModelValidator.Validate(ModelValidationContext mvContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.ValidateNode()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Validate(ModelMetadata metadata, String key, Object model, Boolean alwaysValidateAtTopLevel)
   at FluentValidation.AspNetCore.FluentValidationVisitor.Validate(ModelMetadata metadata, String key, Object model, Boolean alwaysValidateAtTopLevel)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ObjectModelValidator.Validate(ActionContext actionContext, ValidationStateDictionary validationState, String prefix, Object model, ModelMetadata metadata)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.EnforceBindRequiredAndValidate(ObjectModelValidator baseObjectValidator, ActionContext actionContext, ParameterDescriptor parameter, ModelMetadata metadata, ModelBindingContext modelBindingContext, ModelBindingResult modelBindingResult)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<CreateBinderDelegate>g__Bind|0(ControllerContext controllerContext, Object controller, Dictionary`2 arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.BindArgumentsAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Mvc.Internal.MvcEndpointDataSource.<>c__DisplayClass21_0.<CreateEndpoint>b__0(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_1.<UseMiddleware>b__2(HttpContext context)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer.HandleRequest(IISHttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer.HandleRequest(IISHttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer.<>c.<HandleRequest>b__26_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by JeremySkinner** [comment]
Your call to `WithMessage` is incorrect. The call to your localizer must be within a callback. Your current implementation *immediately calls the localizer as soon as you instantiate the validator*. 

You have this: `WithMessage(localizer.GetLocalizedString("Student Name should be less than 10 chars"));` 

It must be this: `WithMessage(x => localizer.GetLocalizedString("Student Name should be less than 10 chars"));`

**Comment by Sandeep321** [comment]
Thank you so much for spending time and pointing out the problem. Little silly mistake. Yes, it works as expected when the localizer is called within a callback. Updated the code and closing this issue.
