### ISSUE TITLE
ShouldHaveValidationErrorFor throws NullReferenceException

### ISSUE THREAD

**Issue by CasperWSchmidt** [JeremySkinner/FluentValidation#1266]
### System Details

- FluentValidation version: 8.5.1

### Issue Description
I have the same issue as in #953 which was never really resolved (author just closed it without any comments).

Test:
```
public class TransactionValidatorTest
{
    private readonly TransactionValidator validator;

    public TransactionValidatorTest()
    {
        validator = new TransactionValidator();
    }

    [Fact]
    public void ShouldHaveErrorWhenAccountAmountIsNull()
    {
        validator.ShouldHaveValidationErrorFor(transaction => transaction.AccountAmount, null as decimal?);
    }
}
```
Validator:
```
public class TransactionValidator : AbstractValidator<RawTransaction>
{
    public TransactionValidator()
    {
        //Basic rules for properties
        RuleFor(x => x.Priority).NotNull();
        RuleFor(x => x.Custodian).NotNull();
        RuleFor(x => x.Account).NotNull();
        RuleFor(x => x.Depository).NotNull().Unless(transaction =>
            transaction.TransactionType == TransactionType.DebetInterestEnum ||
            transaction.TransactionType == TransactionType.InsertWithdrawalEnum ||
            transaction.TransactionType == TransactionType.ManagementFeeEnum);
        RuleFor(x => x.TradeDate).NotEmpty();
        RuleFor(x => x.ValueDate).NotEmpty();
        RuleFor(x => x.Asset).NotNull().Unless(transaction =>
            transaction.TransactionType == TransactionType.DebetInterestEnum ||
            transaction.TransactionType == TransactionType.InsertWithdrawalEnum ||
            transaction.TransactionType == TransactionType.ManagementFeeEnum);
        RuleFor(x => x.AssetType).NotNull().Equal(x => x.Asset.Type).Unless(transaction =>
            transaction.TransactionType == TransactionType.DebetInterestEnum ||
            transaction.TransactionType == TransactionType.InsertWithdrawalEnum ||
            transaction.TransactionType == TransactionType.ManagementFeeEnum);
        RuleFor(x => x.AssetCurrencyCode).NotNull().Unless(transaction =>
            transaction.TransactionType == TransactionType.DebetInterestEnum ||
            transaction.TransactionType == TransactionType.InsertWithdrawalEnum ||
            transaction.TransactionType == TransactionType.ManagementFeeEnum);
        RuleFor(x => x.AccountAmount).NotNull();
        //Logical rules for transactions
        RuleFor(x => x).Must(AccountAmountIsValid);
        RuleFor(x => x).Must(transaction => transaction.ValueDate >= transaction.TradeDate);
        RuleFor(x => x).Must(AccountAmountAndNominalOppositeSign);
        //Include sub-validators for specific transaction types
        When(x => x.TransactionType == TransactionType.BuySellEnum, () =>
            Include(new BuySellValidator()));
        When(x => x.TransactionType == TransactionType.CouponInterestEnum, () =>
            Include(new CouponInterestValidator()));
        When(x => x.TransactionType == TransactionType.ManagementFeeEnum, () =>
            Include(new FeeValidator()));
        When(x => x.TransactionType == TransactionType.DrawingEnum, () =>
            Include(new DrawingValidator()));
    }
... private helper-functions removed for simplicity
}
```
Almost all the tests using `ShouldNotHaveValidationErrorFor` succeeds. Example:
```
[Theory]
[InlineData(TransactionType.DebetInterestEnum)]
[InlineData(TransactionType.InsertWithdrawalEnum)]
[InlineData(TransactionType.ManagementFeeEnum)]
public void ShouldNotHaveErrorWhenAssetCurrencyCodeIsNull(TransactionType transactionType)
{
    var rawTransaction = new RawTransaction
    {
        TransactionType = transactionType
    };
    validator.ShouldNotHaveValidationErrorFor(transaction => transaction.AssetCurrencyCode, rawTransaction);
}
```
Also some of the `ShouldHaveValidationErrorFor` works. Example:
```
[Theory]
[InlineData(TransactionType.BuySellEnum)]
[InlineData(TransactionType.DividendEnum)]
[InlineData(TransactionType.DrawingEnum)]
[InlineData(TransactionType.CouponInterestEnum)]
[InlineData(TransactionType.PoolDrawingEnum)]
public void ShouldHaveErrorWhenAssetTypeDoesNotMatchTypeOnAsset(TransactionType transactionType)
{
    var rawTransaction = new RawTransaction
    {
        TransactionType = transactionType,
        Asset = new BasicData
        {
            Type = AssetType.BondEnum
         },
        AssetType = AssetType.ShareEnum
    };
    validator.ShouldHaveValidationErrorFor(transaction => transaction.AssetType, rawTransaction);
}
```

Stacktrace:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at lambda_method(Closure , RawTransaction )
   at FluentValidation.Internal.Extensions.<>c__DisplayClass9_0`2.<CoerceToNonGeneric>b__0(Object x) in /home/jskinner/code/FluentValidation/src/FluentValidation/Internal/Extensions.cs:line 155
   at FluentValidation.Validators.EqualValidator.GetComparisonValue(PropertyValidatorContext context) in /home/jskinner/code/FluentValidation/src/FluentValidation/Validators/EqualValidator.cs:line 65
   at FluentValidation.Validators.EqualValidator.IsValid(PropertyValidatorContext context) in /home/jskinner/code/FluentValidation/src/FluentValidation/Validators/EqualValidator.cs:line 52
   at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context) in /home/jskinner/code/FluentValidation/src/FluentValidation/Validators/PropertyValidator.cs:line 55
   at FluentValidation.Internal.PropertyRule.InvokePropertyValidator(ValidationContext context, IPropertyValidator validator, String propertyName) in /home/jskinner/code/FluentValidation/src/FluentValidation/Internal/PropertyRule.cs:line 423
   at FluentValidation.Internal.PropertyRule.Validate(ValidationContext context)+MoveNext() in /home/jskinner/code/FluentValidation/src/FluentValidation/Internal/PropertyRule.cs:line 282
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in /home/jskinner/code/FluentValidation/src/FluentValidation/AbstractValidator.cs:line 115
   at FluentValidation.AbstractValidator`1.FluentValidation.IValidator.Validate(ValidationContext context) in /home/jskinner/code/FluentValidation/src/FluentValidation/AbstractValidator.cs:line 69
   at FluentValidation.DefaultValidatorExtensions.Validate[T](IValidator`1 validator, T instance, IValidatorSelector selector, String ruleSet) in /home/jskinner/code/FluentValidation/src/FluentValidation/DefaultValidatorExtensions.cs:line 882
   at FluentValidation.TestHelper.ValidationTestExtension.TestValidate[T](IValidator`1 validator, T objectToTest, String ruleSet) in /home/jskinner/code/FluentValidation/src/FluentValidation/TestHelper/ValidatorTestExtensions.cs:line 107
   at FluentValidation.TestHelper.ValidationTestExtension.ShouldHaveValidationErrorFor[T,TValue](IValidator`1 validator, Expression`1 expression, TValue value, String ruleSet) in /home/jskinner/code/FluentValidation/src/FluentValidation/TestHelper/ValidatorTestExtensions.cs:line 41
```

Any idea what is going on? It looks like `validator` is null, but it's initialized in the constructor and works fine for all ?

**Comment by JeremySkinner** [comment]
The issue isn't that the validator is null, but rather you're trying to access a null sub-property:

```
RuleFor(x => x.AssetType).NotNull().Equal(x => x.Asset.Type)
```

Here you're trying to access `x.Asset.Type`, but `Asset` is null, so the runtime will correctly throw a NullReferenceException. This isn't a FluentValidation issue, it's just normal .NET behaviour for trying to access a null reference. You ned a `When` condition to catch the null.

```
RuleFor(x => x.AssetType).NotNull().Equal(x => x.Asset.Type).Unless(...)
                .When(x => x.Asset != null);
```

**Comment by CasperWSchmidt** [comment]
Ah, of course. I don't know why, but I guess I thought the test-helper would return immediately - only checking the given property. My bad.

**Comment by JeremySkinner** [comment]
The test helper performs a full call to `Validate` and then looks at all the results that come back to see if the specified errors are present in the results. `validator.ShouldHaveValidatotionErrorFor(x => x.AssetType, rawTransaction)` is a shortcut for:

```csharp
var testResult = validator.TestValidate(rawTransaction);
testResult.ShouldHaveValidationErrorFor(x => x.AssetType);
// and you can perform more assertions on the same result, without executing validate multiple times
```

**Comment by CasperWSchmidt** [comment]
Thank you for the clarification :)
