### ISSUE TITLE
ArgumentNullException when using IStringLocalizer in Validator

### ISSUE THREAD

**Issue by Schmaga** [JeremySkinner/FluentValidation#1306]
### System Details

- FluentValidation version: 8.6.0/8.6.1
- Web Framework version: ASP.NET Core 3.1.0

### Issue Description

I do receive an _ArgumentNullException_ when using the _IStringLocalizer_ indexer's second overload inside of a validator as shown in these two variants:

```
// static version
RuleFor(m => m.Name)
    .MaximumLength(100).WithMessage(localizer["Name_MaxLength", 100]);

// callback version
RuleFor(m => m.Name)
    .MaximumLength(100).WithMessage(x => localizer["Name_MaxLength", 100]);
```

The relevant part of the produced stacktrace of the static version is:
```
System.ArgumentNullException : A message must be specified when calling WithMessage. (Parameter 'errorMessage')
   at FluentValidation.Internal.Extensions.Guard(String str, String message, String paramName) in /home/jskinner/code/FluentValidation/src/FluentValidation/Internal/Extensions.cs:line 45
   at FluentValidation.DefaultValidatorOptions.WithMessage[T,TProperty](IRuleBuilderOptions`2 rule, String errorMessage) in /home/jskinner/code/FluentValidation/src/FluentValidation/DefaultValidatorOptions.cs:line 108
   at MyProject.MyValidator..ctor(IStringLocalizer`1 localizer)
```

The callback variant produces the following stacktrace:
```
System.ArgumentNullException : Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.Regex.Match(String input)
   at FluentValidation.Internal.MessageFormatter.BuildMessage(String messageTemplate) in /home/jskinner/code/FluentValidation/src/FluentValidation/Internal/MessageFormatter.cs:line 100
   at FluentValidation.Internal.MessageBuilderContext.GetDefaultMessage() in /home/jskinner/code/FluentValidation/src/FluentValidation/Internal/MessageBuilderContext.cs:line 36
   at FluentValidation.Validators.PropertyValidator.CreateValidationError(PropertyValidatorContext context) in /home/jskinner/code/FluentValidation/src/FluentValidation/Validators/PropertyValidator.cs:line 101
   at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context) in /home/jskinner/code/FluentValidation/src/FluentValidation/Validators/PropertyValidator.cs:line 58
   at FluentValidation.Internal.PropertyRule.InvokePropertyValidator(ValidationContext context, IPropertyValidator validator, String propertyName) in /home/jskinner/code/FluentValidation/src/FluentValidation/Internal/PropertyRule.cs:line 423
   at FluentValidation.Internal.PropertyRule.Validate(ValidationContext context)+MoveNext() in /home/jskinner/code/FluentValidation/src/FluentValidation/Internal/PropertyRule.cs:line 282
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in /home/jskinner/code/FluentValidation/src/FluentValidation/AbstractValidator.cs:line 115
   at FluentValidation.AbstractValidator`1.FluentValidation.IValidator.Validate(ValidationContext context) in /home/jskinner/code/FluentValidation/src/FluentValidation/AbstractValidator.cs:line 69
   at FluentValidation.DefaultValidatorExtensions.Validate[T](IValidator`1 validator, T instance, IValidatorSelector selector, String ruleSet) in /home/jskinner/code/FluentValidation/src/FluentValidation/DefaultValidatorExtensions.cs:line 882
   at FluentValidation.TestHelper.ValidationTestExtension.TestValidate[T](IValidator`1 validator, T objectToTest, String ruleSet) in /home/jskinner/code/FluentValidation/src/FluentValidation/TestHelper/ValidatorTestExtensions.cs:line 107
   at FluentValidation.TestHelper.ValidationTestExtension.ShouldHaveValidationErrorFor[T,TValue](IValidator`1 validator, Expression`1 expression, TValue value, String ruleSet) in /home/jskinner/code/FluentValidation/src/FluentValidation/TestHelper/ValidatorTestExtensions.cs:line 41
```

The second overload of the indexer should function like a _string.Format()_ wrapped around the specified indexed string. As a workaround, if I write the _string.Format()_ myself like this, then it works:
```
// static version
RuleFor(m => m.Name)
    .MaximumLength(2000).WithMessage(string.Format(localizer["Name_MaxLength"], 2000));

// callback version
RuleFor(m => m.Name)
    .MaximumLength(2000).WithMessage(x => string.Format(localizer["Name_MaxLength"], 2000));
```

Is this a bug or am I doing something wrong? I used Unit Tests to reproduce it, that's why the test helper appears in the second stacktrace.

**Comment by JeremySkinner** [comment]
Hi there,

Firstly, you should *not* use the static version. The string localizer should always be invoked within a callback, this ensures that the correct culture is evaluated at the time validation occurs. The static version will evalulate the culture at the time the validator is *constructed*. These will not necessarily be the same. Always use a callback for this.

For the callback version, the stack trace is essentially saying that your StringLocalizer isn't returning anything for "Name_MaxLength"). Make sure you actually have a value for "Name_MaxLength" in your localization source - it can't return null.

**Comment by Schmaga** [comment]
Your guess was spot-on. 

The problem was two-fold: I was using the callback version in almost all parts of the code, but forgot one single line where I still had the static usage, leading to the error. And in my tests, I was using mocks and forgot to mock the second indexer... Damn. So much for even messing up the double-checks :)

Sorry for the inconvenience. Going to close this.

**Comment by JeremySkinner** [comment]
Great, glad you got it sorted
