### ISSUE TITLE
Unit Testing Errors on Custom PropertyValidators

### ISSUE THREAD

**Issue by dgspurgin** [JeremySkinner/FluentValidation#136]
When I try to run this test:

(I can confirm provider is not null)
provider = _testingRepo.GetProvider(1);
ValidationResult validationResult = validator.Validate(provider);

Test Name:	YesErrorWhenNameIsNull
Test FullName:	NEW_ECAP_API.Tests.Validators.ProviderValidatorTest.YesErrorWhenNameIsNull
Test Source:	{my machine}\NEW_ECAP_API.Tests\Validators\ProviderValidatorTest.cs : line 33
Test Outcome:	Failed
Test Duration:	0:00:00.4250637

Result Message:	
Test method NEW_ECAP_API.Tests.Validators.ProviderValidatorTest.YesErrorWhenNameIsNull threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
Result StackTrace:	
at NEW_ECAP_API.Data.Validators.CustomDateTimeISO8601Validator`1.IsValid(PropertyValidatorContext context) in {my machine}\NEW_ECAP_API.Data\Validators\CustomISO8601Validator.cs:line 22
   at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context) in c:\Projects\FluentValidation\src\FluentValidation\Validators\PropertyValidator.cs:line 71
   at FluentValidation.Internal.PropertyRule.<Validate>d__10.MoveNext() in c:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 241
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in c:\Projects\FluentValidation\src\FluentValidation\AbstractValidator.cs:line 113
   at FluentValidation.Validators.ChildCollectionValidatorAdaptor.<Validate>b__5(Tuple`2 tuple) in c:\Projects\FluentValidation\src\FluentValidation\Validators\ChildCollectionValidatorAdaptor.cs:line 48
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at FluentValidation.Internal.PropertyRule.<Validate>d__10.MoveNext() in c:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 245
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in c:\Projects\FluentValidation\src\FluentValidation\AbstractValidator.cs:line 113
   at NEW_ECAP_API.Tests.Validators.ProviderValidatorTest.YesErrorWhenNameIsNull() in {my machine}\NEW_ECAP_API.Tests\Validators\ProviderValidatorTest.cs:line 37

**Comment by JeremySkinner** [comment]
So it looks like you're calling the wrong overload of Validate - there's one that takes the instance to validate, and there's one that takes a ValidationContext. I really need to see a full code sample though to see what's going on.  What's the type of "provider"? How is the validator defined?

**Comment by dgspurgin** [comment]
REALLY appreciate your help, Jeremy!

-------------------------------
The type of provider object:
'Provider'

-------------------------------
The validator class:

public class ProviderValidator : AbstractValidator<Provider>
{
	public ProviderValidator()
        {
        ...
        
        
The unit test: (I've tried both ways and am getting null error)     
    [TestClass]
    public class ProviderValidatorTest : BaseApiTest
    {

        private ProviderValidator validator;
        private Provider provider;
        
        public ProviderValidatorTest() : base() {
            validator = new ProviderValidator();
        }

        [TestMethod()]
        public void YesErrorWhenNameIsNull()
        {

           provider = _testingRepo.GetProvider(1);

	   // W/out using fluentv's helper
           // ValidationResult validationResult = validator.Validate(provider);
           // Assert.IsTrue(validationResult.IsValid);

	   // Using helper method
           validator.ShouldHaveValidationErrorFor(Provider => Provider.Name, provider);
        }
...

**Comment by JeremySkinner** [comment]
Not sure I was clear.

I need to see the *full* code of your CustomISO8601Validator class.

**Comment by dgspurgin** [comment]
You were clear.  My bad.

using FluentValidation.Validators;
using System.Text.RegularExpressions;
using System;
using System.Collections.Generic;
using NEW_ECAP_API.Data.Models;


namespace NEW_ECAP_API.Data.Validators
{

    public class CustomDateTimeISO8601Validator<T> : PropertyValidator
    {
        public CustomDateTimeISO8601Validator()
            : base("{PropertyName}: Invalid format"){
        }
        protected override bool IsValid(PropertyValidatorContext context)
        {
            string dateString = context.PropertyValue.ToString();
            Regex regex = new Regex(@"^(\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\dZ$)");
            Match match = regex.Match(dateString);
            if (match.Success)
            {
                return true;
            }
            return false;
        }
    }

}

**Comment by JeremySkinner** [comment]
Ok so it looks like the NullReferenceException is most likely from this line in your validator:

        string dateString = context.PropertyValue.ToString();

You'll need to do a null check here to see if PropertyValue is null before calling ToString on it.

**Comment by dgspurgin** [comment]
My main provider valiator does not use CustomDateTimeISO8601Validator BUT I have some collections in my provider objects that have their own validators that DO use the the CustomDateTimeISO8601Validator validator...  saw some post about nested validators as I googled about.  Perhaps those post are for me.

(Uh.. you rock)

**Comment by JeremySkinner** [comment]
Yeah, if you have child validators set up for properties on your root-level object, then calling Validate on the top-level validator will validate the entire hierarchy.

**Comment by dgspurgin** [comment]
Where I'm using my ISO8601 validator I've placed them after null / empty checks.  AND I added this to global.asax --->  ValidatorOptions.CascadeMode = CascadeMode.StopOnFirstFailure.  Should it ever receive a call w/ null prop value if it is indeed this way? (am sure there is some user error -- am double checking now).

            RuleFor(x => x.DateOfBirth)
                .NotNull()
                .WithMessage(badRequired)
                .NotEmpty()
                .WithMessage(badRequired)
                .CustomDateTimeISO8601Validator()
                .CustomDateTimeNowOrEarlierValidator()
                .CustomDateTimeMaxChildAgeValidator();

Also... do I need NotNull() checks if I'm doing NotEmpty() checks?

**Comment by JeremySkinner** [comment]
NotEmpty performs a NotNull check too, so you shouldn't need both. If CascadeMode is set to StopOnFirstFailure, then a Null shouldn't be passed to your CustomDateTimeISO8601Validator. Still, I'd recommend you modify the validator to skip validation (and just return true) if the PropertyValue is null (FluentValidation's built-in validators all work this way)

Note that if you set CascadeMode to StopOnFirstFailure in your global.asax, this won't apply to your unit tests. You'll need to set it in your test class's initialization.

**Comment by dgspurgin** [comment]
Thank-you for ALL your help. A little more faith in the kindness of humanit after being assisted by you, Jeremy.  Will do my best to pay it forward.

**Comment by JeremySkinner** [comment]
Glad it's all sorted!
