### ISSUE TITLE
FluentValidation throws NullReferenceException when validation object is null

### ISSUE THREAD

**Issue by sonicflare** [JeremySkinner/FluentValidation#137]
FluentValidation throws NullReferenceException when the object is null

Expected:
ValidationResult with Message "Entity cannot be null"

```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FluentValidation;

namespace ConsoleApplication11
{
    public class Entity
    {
        public string Type { get; set; }
    }

    public class EntityValidator : AbstractValidator<Entity>
    {
        public EntityValidator()
        {
            this.RuleFor(a => a)
             .NotEmpty()
             .WithMessage("Entity cannot be null");


            this.RuleFor(a => a.Type)
                .NotEmpty()
                .WithMessage("Type cannot be null or empty");

        }
    }

    internal class Program
    {
        private static void Main(string[] args)
        {
            Entity entity = null;


            var validator = new EntityValidator();


            validator.Validate(entity);
        }
    }

}
```

Stacktrace:
```
   at lambda_method(Closure , Entity )
   at FluentValidation.Internal.Extensions.<>c__DisplayClass1`2.<CoerceToNonGeneric>b__0(Object x) in c:\Projects\FluentValidation\src\FluentValidation\Internal\Extensions.cs:line 108
   at FluentValidation.Validators.PropertyValidatorContext.get_PropertyValue() in c:\Projects\FluentValidation\src\FluentValidation\Validators\PropertyValidatorContext.cs:line 53
   at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context) in c:\Projects\FluentValidation\src\FluentValidation\Validators\PropertyValidator.cs:line 69
   at FluentValidation.Internal.PropertyRule.InvokePropertyValidator(ValidationContext context, IPropertyValidator validator, String propertyName) in c:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 360
   at FluentValidation.Internal.PropertyRule.<Validate>d__10.MoveNext() in c:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 241
   at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in c:\Projects\FluentValidation\src\FluentValidation\AbstractValidator.cs:line 113
   at FluentValidation.AbstractValidator`1.Validate(T instance) in c:\Projects\FluentValidation\src\FluentValidation\AbstractValidator.cs:line 94
   at ConsoleApplication11.Program.Main(String[] args) in c:\users\administrator\documents\visual studio 2015\Projects\ConsoleApplication11\Program.cs:line 37
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by JeremySkinner** [comment]
FluentValidation doesn't work that way I'm afraid - you always need to provide a non-null instance for the root-level object being validated. I'll add a friendlier message, rather than having it throw a NRE, but you will need to still provide an instance for validation.

**Comment by sonicflare** [comment]
Hm, ok
But is there a reason, why it should not do that? Isn't checking for null not a validation?

**Comment by JeremySkinner** [comment]
So FluentValidation is designed for validating the properties of an object, not the presence of the object itself. So the most common scenario for FluentValidation is a ViewModel/InputModel scenario, where the object represents the state of a screen, and the properties represent the input fields on the screen. The viewmodel itself would never be null, but the properties on that viewmodel certainly could be.

**Comment by spawluk** [comment]
But what with WebAPI? There is a way to provide no data and input model is null

**Comment by theofanis** [comment]
@spawluk That's the exact problem in my case. The bound model from the JSON payload, let's say in a POST request, is null, so the validator never kicks in, so it needs a custom way to handle this case. Not pretty.

**Comment by LeeCampbell** [comment]
Does seem odd that you need to validate your inputs before passing them to your validation tool (talk about having a dog but barking yourself), but thanks @JeremySkinner for being explicit that this is the expected behaviour.

**Comment by piotrkula-brother** [comment]
Can you please add a better error message. Our validator fails on a complex model and I have no clue why, which model, which rules, which whatever. 

`Object reference not set to an instance of an object.`

Great.

**Comment by AlokArora** [comment]
Having Dependent Rule inside a When() I can still reproduce this behavior.

**Comment by ryanbuening** [comment]
If I have something like this:

```c#
When(x => x.SendMail.Equals("Y"), () =>
{
	RuleFor(x => x.To).NotEmpty();
	RuleFor(x => x.From).NotEmpty();
	RuleFor(x => x.EmailAddress).NotEmpty();
});
```
and SendMail does not have a value, I will get a NullReferenceException. However, if I surround the When() like so:

```c#
When(x => x.SendMail != null, () =>
{
	When(x => x.SendMail.Equals("Y"), () =>
	{
		RuleFor(x => x.To).NotEmpty();
		RuleFor(x => x.From).NotEmpty();
		RuleFor(x => x.EmailAddress).NotEmpty();
	});
});
```

it works as I would expect and I do not get a NRE. I'm new to FluentValidaton and C# in general. Is this the proper way to go about handling validations like this?

**Comment by JeremySkinner** [comment]
No need to have two When calls. Just switch from using .Equals to == and then you won't get a NullReference

**Comment by ryanbuening** [comment]
Not being able to validate against null objects prevents me from using FV. I have nested classes in my ViewModel that can be null.

**Comment by ppenan** [comment]
I have this rule, and even I put null, "", or " " I got the error of null reference. How can I fix it because I have lots of nulls in my model (I need to)...


RuleFor(prestamo => prestamo["sectorEconomico"].ToString()).Cascade(CascadeMode.StopOnFirstFailure).Must((prestamo, type) => { return GenericValidatorType.ValidateType(prestamo["sectorEconomico"].ToString(), typeof(String)); }).MaximumLength(1000);
