### ISSUE TITLE
ShouldHaveValidationErrorFor( ) not working as expected

### ISSUE THREAD

**Issue by vegar** [JeremySkinner/FluentValidation#201]
Take a look at the following xUnit test:

``` cs
using System.Linq;
using FluentValidation;
using FluentValidation.TestHelper;
using Xunit;

namespace Validation.Tests
{
    [Trait("ValidationTests", "ShouldHaveValidationErrorFor")]
    public class ValidationTests
    {
        internal class Address
        {
            public string Street { get; set; }
        }

        internal class Person
        {
            public Address Address { get; set; }
        }

        [Fact(DisplayName = "ShouldHaveValidationErrorFor not working as expected")]
        public void ShouldHAveValidationErrorForNotWorkingAsExpected()
        {
            var person = new Person {Address = new Address {Street = ""}};

            var validator = new InlineValidator<Person>()
                            {
                                v => v.RuleFor(p => p.Address.Street).NotEmpty()
                            };

            var result = validator.Validate(person);
            Assert.False(result.IsValid);
            var errors = result.Errors.Select(e => e.PropertyName);
            Assert.Contains("Address.Street", errors);

            validator.ShouldHaveValidationErrorFor(p => p.Address.Street, person);
        }
    }
}

```

It gives me the following output:

```
Test Name:  ShouldHaveValidationErrorFor not working as expected
Test FullName:  Validation.Tests.ValidationTests.ShouldHAveValidationErrorForNotWorkingAsExpected
Test Source:    C:\Source\Validation.Tests\Class1.cs : line 23
Test Outcome:   Failed
Test Duration:  0:00:00,528

Result1 Name:   ShouldHaveValidationErrorFor not working as expected
Result1 Outcome:    Failed
Result1 Duration:   0:00:00,26
Result1 StackTrace: 
at FluentValidation.TestHelper.ValidationResultTester`2.ShouldHaveValidationError(IEnumerable`1 properties) in C:\projects\FluentValidation\src\FluentValidation\TestHelper\ValidationResultTester.cs:line 47
   at FluentValidation.TestHelper.TestPropertyChain`2.ShouldHaveValidationError() in C:\projects\FluentValidation\src\FluentValidation\TestHelper\TestPropertyChain.cs:line 43
   at FluentValidation.TestHelper.ValidationTestExtension.ShouldHaveError[T,TValue](TestValidationResult`2 testValidationResult) in C:\projects\FluentValidation\src\FluentValidation\TestHelper\ValidatorTestExtensions.cs:line 84
   at FluentValidation.TestHelper.ValidationTestExtension.ShouldHaveValidationErrorFor[T,TValue](IValidator`1 validator, Expression`1 expression, T objectToTest, String ruleSet) in C:\projects\FluentValidation\src\FluentValidation\TestHelper\ValidatorTestExtensions.cs:line 39

```

The two first asserts are not breaking the test: The model is invalid, and it is so because the street property is empty.

I would expect the `ShouldHaveValidationErrorFor( )` method to detect the same thing, but for some reason it don't.

Have I misunderstood something, or are there an error or limitation I'm not aware of?

I'm using Visual Studio 2015 and FluentValidation 6.1

**Comment by JeremySkinner** [comment]
I believe ShouldHaveValidationErrorFor and ShouldNotHaveValidationErrorFor don't support nested properties- you'll need to perform the assertion manually in this case.

**Comment by vegar** [comment]
But is it by intention?

I looks like this is related to the use of a `MemberAccessor< >` to wrap the expression when doing tests and the `GetPropertyName`implementation in  [`ValidationResultTester<>`](https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/TestHelper/ValidationResultTester.cs#L34-L39):

```
string GetPropertyName(IEnumerable<MemberInfo> properties) {
			return string.Join(".", new[] {testValidationResult.MemberAccessor != null ? testValidationResult.MemberAccessor.Member : null}
				.Concat(properties)
				.Where(x => x != null)
				.Select(x => x.Name));
		}
```
If we could have the GetPropertyName return the complete 'train' of accessors, it would work as expected. At least according to my experiments :-) I'm not sure where the modification would fit the best, though...
