### ISSUE TITLE
Custom PropertyValidator error messages don't show in ASP.NET Core

### ISSUE THREAD

**Issue by ajbeaven** [JeremySkinner/FluentValidation#432]
While I have got my PropertyValidator correctly adding errors to the ModelState using the code below, I'm finding that the errors in the ModelState do not have an associated ErrorMessage as it is defined in the call to the base constructor in `MustBeUniqueEmailAddressPropertyValidator` below.

I haven't found anyone else complaining about issues like this before and I know the ASP.NET Core implementation of FluentValidation is relatively new, so I wondered whether there's perhaps a bug with this? Or perhaps it doesn't support generic or abstract Validators?

I've added the code below that might be relevant.

Command and its validator:
```
public abstract class RegisterViewModel
{
	public string EmailAddress { get; set; }
	public string Password { get; set; }
	public string FirstName { get; set; }
	public string LastName { get; set; }
}

public class RegisterTalentViewModel : RegisterViewModel
{
}

public abstract class RegisterValidator<TUser, TCommand> : AbstractValidator<TCommand>
	where TUser : User
	where TCommand : RegisterViewModel
{
	protected RegisterValidator(IDbContextFactory contextFactory)
	{
		RuleFor(cmd => cmd.EmailAddress)
			.NotEmpty()
			.EmailAddress()
			.SetValidator(new MustBeUniqueEmailAddressPropertyValidator<TUser>(contextFactory));

		RuleFor(cmd => cmd.Password).NotEmpty();
		RuleFor(cmd => cmd.FirstName).NotEmpty();
		RuleFor(cmd => cmd.LastName).NotEmpty();
	}
}

public class RegisterTalentValidator : RegisterValidator<ActorUser, RegisterTalentViewModel>
{
	public RegisterTalentValidator(IDbContextFactory contextFactory)
		: base(contextFactory)
	{
	}
}
```

Property validator:
```
public class MustBeUniqueEmailAddressPropertyValidator<TUser> : PropertyValidator
	where TUser : User
{
	private readonly IDbContextFactory _contextFactory;

	public MustBeUniqueEmailAddressPropertyValidator(IDbContextFactory contextFactory)
		: base("This email address is already registered. Please login")
	{
		_contextFactory = contextFactory;
	}

	protected override bool IsValid(PropertyValidatorContext context)
	{
		using (var dbContext = _contextFactory.Create())
		{
			var emailAddress = (string)context.PropertyValue;
			return !dbContext.Users.OfType<TUser>().Any(u => u.EmailAddress == emailAddress);
		}
	}
}
```

Using Simple Injector IoC container and applying a global filter:
```
services
	.AddMvc()
	.AddMvcOptions(options => options.Filters.Add(new ValidateInputFilter()))
	.AddFluentValidation(fv => fv.ValidatorFactory = new SimpleInjectorValidatorFactory(iocContainer));

iocContainer.Register(typeof(IValidator<>), new[] { typeof(Startup).GetTypeInfo().Assembly });
```

Here's the filter
```
public class ValidateInputFilter : IActionFilter
{
	public ValidateInputFilter()
	{
	}

	public void OnActionExecuting(ActionExecutingContext context)
	{
		if (context.ModelState.IsValid)
			return;

		// here, error.ErrorMessage is an empty string
		context.Result = new BadRequestObjectResult(
			from kvp in context.ModelState
			from error in kvp.Value.Errors
			let key = kvp.Key
			select new ValidationError(ValidationError.Type.Input, null, key == null ? "" : char.ToLowerInvariant(key[0]) + key.Substring(1), error.ErrorMessage));
	}

	public void OnActionExecuted(ActionExecutedContext context)
	{
		// This filter doesn't do anything post action.
	}
}
```

When I look through the ModelState object inside ValidateInputFilter, I see an exception inside `context.ModelState[0].Value.Errors[0]`:

> Could not create an instance of type MyApp.ViewModels.RegisterViewModel. Type is an interface or abstract class and cannot be instantiated. Path 'emailAddress', line 1, position 16.

Stacktrace:
```
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
```

**Comment by ajbeaven** [comment]
Urgh, found it. When I was testing out previous functionality, I switched the argument parameter of the controller action to use the abstract `RegisterViewModel`:

```
public async Task<IActionResult> RegisterTalent([FromBody] RegisterViewModel viewModel)
{
	// ...
}
```

Switching this to the concrete definition fixed the issue with the missing error message. To be honest, I'm surprised this executed without a runtime exception (other than the internal one inside the ModelState).

Anyway, hope this helps someone else at some point!

**Comment by JeremySkinner** [comment]
Glad you found the cause.
