### ISSUE TITLE
RuleForEach doesn't work for non properties

### ISSUE THREAD

**Issue by jlVidal** [JeremySkinner/FluentValidation#479]
```
    public class DynamicValidator<T> : AbstractValidator<IDictionary<string, object>>
    {
        private readonly IServiceProvider _serviceProvider;

        public DynamicValidator(IServiceProvider serviceProvider)
        {
            this._serviceProvider = serviceProvider;

            RuleForEach(model => model.AsEnumerable()).SetValidator(new PropertyExistChecker<T>());
        }
    }
```
```
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Could not apply an Indexer because the property chain is empty.
  Source=FluentValidation
  StackTrace:
   at FluentValidation.Internal.PropertyChain.AddIndexer(Object indexer)
   at FluentValidation.Internal.CollectionPropertyRule`1.InvokePropertyValidator(ValidationContext context, IPropertyValidator validator, String propertyName)
   at FluentValidation.Internal.PropertyRule.<Validate>d__60.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FluentValidation.Results.ValidationResult..ctor(IEnumerable`1 failures)
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context)
   at PM.WebApi.Controllers.DynamicValidator`1.Validate(ValidationContext`1 context) in E:\git\ProfileManagement\PM.WebApi\Util\DynamicValidator.cs:line 48
   at FluentValidation.AbstractValidator`1.Validate(T instance)
   at PM.WebApi.Controllers.PersonalController.UpdatePair(Int32 clientId, Dictionary`2 formData) in E:\git\ProfileManagement\PM.WebApi\Controllers\PersonalController.cs:line 61
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()

```

**Comment by JeremySkinner** [comment]
Yep, that's expected. 

Building the error message requires a name that's associated with the rule....for properties this is the property's name, but in this case it can't work out what to use. You just need to explicitly specify the name:

```
RuleForEach(model => model.AsEnumerable()).SetValidator(new PropertyExistChecker<T>()).OverridePropertyName("Whatever");
```

**Comment by kripergvg** [comment]
@JeremySkinner can you add a more human-friendly message? :)

**Comment by JeremySkinner** [comment]
Yes. I can do that for the next release. Please open a new issue if you run into any further issues, thanks.
