### ISSUE TITLE
Mock an AbstractValidator ValidateAndThrow using NSubstitute

### ISSUE THREAD

**Issue by nrea** [JeremySkinner/FluentValidation#536]
I am having some trouble trying to mock the call to ValidateAndThrow method using NSubstitute. I want to configure the call to throw an exception and my unit test looks like: 

```
        [Test]
        [ExpectedException(typeof(ValidationException), ExpectedMessage = "Total Amount was invalid.")]
        public void SaleTest_SaleValidatorException()
        {
            var validatorMock = Substitute.For<IValidator<SaleRequestData>>();
            validatorMock.When(a => a.ValidateAndThrow(Arg.Any<SaleRequestData>())).Do(e =>
                {
                    throw new ValidationException("Total Amount was invalid.");
                });

            _payService.Sale(_merchantAccountData, _saleRequestData, _cardData, _order, null);
        }
```

The error I am getting is and happens on the " validatorMock.When" line in code above: 

> An unexpected exception type was thrown
> Expected: FluentValidation.ValidationException
>  but was: System.NullReferenceException : Object reference not set to an instance of an object.
>    at FluentValidation.DefaultValidatorExtensions.ValidateAndThrow[T](IValidator`1 validator, T instance, String ruleSet)
>    at Cayan.Core.Payments.Test.PayServiceTest.<SaleTest_SaleValidatorException>b__4(IValidator`1 a) in c:\Git\cayan-main-payservice\Cayan.Core\Cayan.Core.Payments.Test\PayServiceTest.cs:line 104
>    at Cayan.Core.Payments.Test.PayServiceTest.SaleTest_SaleValidatorException() in c:\Git\cayan-main-payservice\Cayan.Core\Cayan.Core.Payments.Test\PayServiceTest.cs:line 104

**The validator class I have is a singleton with no public parameter-less constructor:** 

```
   public class SaleRequestDataValidator : AbstractValidator<SaleRequestData>
    {
        private const string TotalAmountName = "Total Amount";
        private const string TaxAmountName = "Tax Amount";
         private static readonly Lazy<SaleRequestDataValidator> instance = new Lazy<SaleRequestDataValidator>(() => new SaleRequestDataValidator());

        public static SaleRequestDataValidator Instance
        {
            get
            {
                return instance.Value;
            }
        }

        private SaleRequestDataValidator()
        {
            // Check that network type is valid
            this.RuleFor(r => r.NetworkType)
                .Must(
                    networkType => (networkType == NetworkType.Credit || networkType == NetworkType.Debit || networkType == NetworkType.Gift))
                .WithMessage(networkType => string.Format(ValidationMessages.InvalidNetworkTypeMessage, networkType));

            // Check that transaction amount is valid money and greater than 0
            this.RuleFor(r => r.TotalAmount).MustBeValidMoney(TotalAmountName);
            this.RuleFor(r => r.TotalAmount.Amount).GreaterThan(decimal.Zero).WithName(TotalAmountName);
          
        }
```

**The PayService class looks like:** 

```
public class PayService : TransactionServiceBase, IPayService
    {

        private IValidator<SaleRequestData> _saleValidator;
        private IValidator<CardData> _cardDataValidator;
        private ISmartPaymentsService _smartPaymentsService;
        private static ILog _logger = LogManager.GetLogger(typeof(PayService));
          public PayService(IValidator<SaleRequestData> validator, IValidator<CardData> cardData, ISmartPaymentsService smartPaymentsService)
        {
            _saleValidator = validator;
            _cardDataValidator = cardData;
            _smartPaymentsService = smartPaymentsService;
        }

        public GatewayResponse Sale(MerchantAccount merchantAccountData,
                                    SaleRequestData requestData,
                                    CardData cardData,
                                    Order orderData,
                                    string extraData)
        {
              GatewayResponse gatewayResponse = null;
                 // Some code
                 //Validate SaleRequestData
                _saleValidator.ValidateAndThrow(requestData);

                // Some code
            }
            catch (ValidationException validationEx)
            {
                // Log validation error
                _logger.Error(validationEx);
                throw;
            }

            return gatewayResponse;
        }
```

What am I missing here?

**Comment by JeremySkinner** [comment]
ValidateAndThrow is an extension method - you can't mock extension methods.

**Comment by nrea** [comment]
Thanks for quick turnaround Jeremy. So, I changed my code to mock the Validate method called by ValidateAndThrow and I still get the same error. 

```
var validatorMock = Substitute.For<IValidator<SaleRequestData>>();
            ValidationResult result = new ValidationResult(new List<ValidationFailure>()
                                                               {
                                                                   new ValidationFailure("TotalAmount",
                                                                       "Total Amount was invalid.")
                                                               });

            validatorMock.Validate(_saleRequestData).Returns(result);

            _payService = new PayService(validatorMock, _cardDataValidatorMock, _smartPaymentsServiceMock);


            _payService.Sale(_merchantAccountData, _saleRequestData, _cardData, _order, null);
        }
```
My code does work, if I change the call from ValidateAndThrow to Validate. Does this mean there is no way no mock the call to ValidateAndThrow?

**Comment by JeremySkinner** [comment]
You're not mocking the right overload of Validate.

**Comment by JeremySkinner** [comment]
The overload of Validate called by ValidateAndThrow is the one that takes a ValidationContext[T]. See here: https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/DefaultValidatorExtensions.cs#L872

**Comment by nrea** [comment]
Ah yes, sorry missed that simple thing. It all works now. 

```
 var validatorMock = Substitute.For<IValidator<SaleRequestData>>();
            ValidationResult result = new ValidationResult(new List<ValidationFailure>()
                                                               {
                                                                   new ValidationFailure("TotalAmount",
                                                                       "Total Amount was invalid.")
                                                               });

            validatorMock.Validate(Arg.Any<ValidationContext>()).Returns(result);

            _payService = new PayService(validatorMock, _cardDataValidatorMock, _smartPaymentsServiceMock);


            _payService.Sale(_merchantAccountData, _saleRequestData, _cardData, _order, null);
```

Thanks again for your help on this.
