### ISSUE TITLE
Release# 7.3.1 throws System.InvalidOperationException: 'Sequence contains more than one matching element' exception

### ISSUE THREAD

**Issue by Arash-Sabet** [JeremySkinner/FluentValidation#648]
Upgraded the package to 7.3.1 and started receiving the exception right at ```app.UseMvc();``` line in ```Configure``` method below:
```
public void Configure(
			IApplicationBuilder app,
			IHostingEnvironment env,			
			ILoggerFactory loggerFactory)
		{
			app.UseAuthentication();
			app.UseStaticFiles();
			loggerFactory.AddConsole(Configuration.GetSection("Logging")).AddDebug().AddSerilog();

			app.UseResponseCompression();

			app.UseMvc();

		}
```
Exception's stack trace is per below:
```
at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
  at FluentValidation.AspNetCore.FluentValidationObjectModelValidator..ctor(IModelMetadataProvider modelMetadataProvider, IList`1 validatorProviders, Boolean runMvcValidation)
  at FluentValidation.AspNetCore.FluentValidationMvcExtensions.<>c__DisplayClass1_0.<RegisterServices>b__0(IServiceProvider s)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
  at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
  at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
  at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
  at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
  at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
  at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app)
  at MyApplication.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\Projects\MyApplication\Startup.cs:line 94
```

**Comment by JeremySkinner** [comment]
I can't reproduce this - it doesn't happen in any of my tests so I'm going to need a bit more info from you to see what's going on:

- Which version of Microsoft.AspNet.Mvc do you have installed?
- Please post the contents of your ConfigureServices method (specifically I need to see where you're calling .AddFluentValidation and any FV-related configuration)
- Do you have any custom validator providers registered?

**Comment by Arash-Sabet** [comment]
Here is the info:

- ```<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.1" />```
- ```ConfigureServices``` looks like the code snippet below. In this code ```Class1``` and ```Class2``` reside in two different assemblies. Having said that, ```Class2``` is implementing an interface which is hosted within the same assembly as ```Class1``` implemented.

```
public void ConfigureServices(IServiceCollection services)
		{
			// Add framework services.

			//Adding options to pass application settings entries along.
			services
				.AddOptions()
				.AddMediatRToScope()						
				.AddResponseCompression(options => 
				{
					options.EnableForHttps = true;
					options.Providers.Add<GzipCompressionProvider>();
				})				
				.AddConfigurations(Configuration);

			
			services.AddMvc(options => options.Conventions.Insert(0, new RouteConvention { Template = Configuration["Routing:Template"] }))
				.AddFluentValidation(configuration => configuration.RegisterValidatorsFromAssemblyContaining<Class1>())
				.AddFluentValidation(configuration => configuration.RegisterValidatorsFromAssemblyContaining<Class2>());

		}
```
- There are no other custom validator providers registered. All validations take place through fluentvalidation library only.
- No, ```ConfigureServices``` is called only once.

Hope it helps!

**Comment by JeremySkinner** [comment]
Yep, that's your problem - you're call AddFluentValidation twice, which ends up registering all the components twice. You should only call AddFluentValidation once (but you c an call RegisterValidators multiple times:

```
services.AddMvc()
	.AddFluentValidation(configuration => { configuration.RegisterValidatorsFromAssemblyContaining<Class1>()
.RegisterValidatorsFromAssemblyContaining<Class2>()
});
```

**Comment by Arash-Sabet** [comment]
@JeremySkinner Thanks. the issue resolved.
