### ISSUE TITLE
Given key not found - after upgrade from 7.3.3 to 7.3.4

### ISSUE THREAD

**Issue by topnguyen** [JeremySkinner/FluentValidation#658]
I use AspNetCore 2

Installed SDK 2.1.3

The below is exception info
```csharp
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at FluentValidation.AspNetCore.FluentValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at FluentValidation.AspNetCore.ValidationVisitorFork.VisitComplexType(IValidationStrategy defaultStrategy)
   at FluentValidation.AspNetCore.ValidationVisitorFork.Visit(ModelMetadata metadata, String key, Object model)
   at FluentValidation.AspNetCore.ValidationVisitorFork.VisitChildren(IValidationStrategy strategy)
   at FluentValidation.AspNetCore.FluentValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at FluentValidation.AspNetCore.ValidationVisitorFork.VisitComplexType(IValidationStrategy defaultStrategy)
   at FluentValidation.AspNetCore.ValidationVisitorFork.Visit(ModelMetadata metadata, String key, Object model)
   at FluentValidation.AspNetCore.FluentValidationObjectModelValidator.Validate(ActionContext actionContext, ValidationStateDictionary validationState, String prefix, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.<BindModelAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()
```

**Comment by JeremySkinner** [comment]
Can you provide a sample project that reproduces the issue?

**Comment by topnguyen** [comment]
Hi Jeremy,

Thank for your quick response.

I use Fluent Validation in [Monkey Repo](https://github.com/stssoftware/Monkey)

I just revert to version 7.3.3, please upgrade to 7.3.4 and see the error detail

**Comment by JeremySkinner** [comment]
Unfortunately that project doesn't built on a fresh checkout and I don't have time to diagnose why. Can you send me a small, cutdown project that just reproduces this specific issue? Thanks.

**Comment by topnguyen** [comment]
Ok Jeremy, I will create a small project and try to reproduce the issue in advance.
If still face it, I reopen this ticket.

**Comment by JeremySkinner** [comment]
Perfect, thanks!

**Comment by topnguyen** [comment]
Hi Jeremy,

I found the key not found issue occur at the line 190 in the file `FluentValidationObjectModelValidator.cs` (project `FluentValidation.AspNetCore`)

```csharp
	var skip = Context.HttpContext.Items["_FV_SKIP"] as HashSet<object>;
```

Therefore, I miss config something to have key `_FV_SKIP` or would you will add more logic check key existing.

**Comment by JeremySkinner** [comment]
HttpContext.Items is supposed to return null if the key isn't found (rather than throwing a KeyNotFound exception), and this is what happens in my tests.

This is really why I need you to send me a sample project so I can look at what's different. My guess is there's a version difference in asp.net core somewhere (where they internally switched from Hashtable to Dictionary), but I need to find out where the mismatch is happening. So if you could still send me that sample project that would be very helpful.

**Comment by JeremySkinner** [comment]
Issue is the ItemsDictionary class in Microsoft.AspnetCore.Http.Internal, but it looks like the current version correctly returns null:

https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http/Internal/ItemsDictionary.cs#L24-L33

Could you confirm which version of the Microsoft.AspNetCore.Http.Abstractions package you have installed?

**Comment by topnguyen** [comment]
Hi Jeremy,

Your guess is correct, in the past, I was facing the difference version issue.

My `Microsoft.AspNetCore.Http.Abstractions` version `2.0.1` latest, but your version is `2.0.0`.

![2018-01-03_19-40-22](https://user-images.githubusercontent.com/15808788/34520994-f33cb230-f0bd-11e7-9590-e17e6f97885f.png)

**Comment by JeremySkinner** [comment]
I'm actually using 2.0.1 too in my tests and it doesn't throw the exception (the 2.0.0 referenced by FluentValidation.AspnetCore is just the minimum version it'll build against).

**Comment by topnguyen** [comment]
I only face the issue when I make an ajax request by `Jquery DataTable` server-side paging.
It still works well for Microsoft.jQuery.Unobtrusive.Validation.
Do you have any idea?

**Comment by JeremySkinner** [comment]
Not at the moment. I really need more information to go on...I don't think I can help any further until you can send me a working sample.

**Comment by topnguyen** [comment]
It takes time to build and give you the small project because my project integrates many services/libraries and auto-generate features.
I just close the issue due to my specific project.

**Comment by JeremySkinner** [comment]
Ok, well that's a shame. I literally just need a basic asp.net project that shows this 1 specific issue.

In reality this doesn't actually look like a problem with FluentValidation, but how HttpContext.Items is behaving in your project.

One other thing you can check is if you try and access HttpContext.Items with a non-existent key (eg HttpContext.Items["foo"]) does this return null, or does this throw an exception? Is this behaviour different between a regular controller and an Api controller?

**Comment by topnguyen** [comment]
I see, but I already test something like your mention `HttpContext.Items["foo"]` in a Controller of my project, still return `null` if the key does not exist.

Actually in your unit test and fresh AspNetCore project not have this issue and can't reproduce it.

I have no idea too, it will take much time to find out what is the reason because my project integrates many services and make some conflict when I upgrade to version 7.3.4.

That why I close the issue. 

I will let you known if during develop time I find what is exactly root cause.
