### ISSUE TITLE
Validate NullReferenceException

### ISSUE THREAD

**Issue by Szczepanek** [JeremySkinner/FluentValidation#798]
Hi,
I got this error each time, with lack of information of exception details.
StackTrace looks like this:   at lambda_method(Closure , CreateAddressRequestForm )
   at FluentValidation.Internal.Extensions.<>c__DisplayClass9_0`2.<CoerceToNonGeneric>b__0(Object x)
   at FluentValidation.Validators.PropertyValidatorContext.<>c__DisplayClass24_0.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at FluentValidation.Validators.NotEmptyValidator.IsValid(PropertyValidatorContext context)
   at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context)
   at FluentValidation.Validators.DelegatingValidator.Validate(PropertyValidatorContext context)
   at FluentValidation.Internal.PropertyRule.InvokePropertyValidator(ValidationContext context, IPropertyValidator validator, String propertyName)
   at FluentValidation.Internal.PropertyRule.<Validate>d__60.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FluentValidation.Results.ValidationResult..ctor(IEnumerable`1 failures)
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context)
   at FluentValidation.AbstractValidator`1.Validate(T instance)
   at FluentValidation.AbstractValidator`1.FluentValidation.IValidator.Validate(Object instance)
   at Activities.Validate`1.ValidateData(CodeActivityContext context) in Activities\Validate.cs:line 63
   at Activities.Validate`1.Execute(CodeActivityContext context) in Activities\Validate.cs:line 17
   at System.Activities.CodeActivity`1.InternalExecute(ActivityInstance instance, ActivityExecutor executor, BookmarkManager bookmarkManager)
   at System.Activities.ActivityInstance.Execute(ActivityExecutor executor, BookmarkManager bookmarkManager)
   at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation)

**Comment by JeremySkinner** [comment]
Hi, you're going to need to provide more information than that for me to help.

How is your validator defined? How are you calling it?

**Comment by Szczepanek** [comment]
i think that call and definition of validator is OK, problem appears somewhere deeper. Cant tell if it helps anywhay but that is all i have 
![image](https://user-images.githubusercontent.com/4491129/41721386-01028778-7566-11e8-8fab-5e6385534928.png)

**Comment by JeremySkinner** [comment]
It suggests to me that there's a problem with how the validator is defined or being executed. I really can't help though if you don't post the code...

**Comment by Szczepanek** [comment]
private ValidationResult ValidateData(CodeActivityContext context)
        {
            var dataToValidate = DataToValidate.Get(context);

            var validator = GetValidator(context, dataToValidate);
            if(validator == null)
                throw new ArgumentException(string.Format("Validator for type: '{0}' could not be create by Factory.",
                    typeof (TData)));
            
            **return validator.Validate(dataToValidate);**
        }

        private static IValidator GetValidator(CodeActivityContext context, TData dataToValidate)
        {
            return context.GetExtension<IValidatorFactory>().GetValidator(dataToValidate.GetType());
        }

**Comment by JeremySkinner** [comment]
As I said before, I need to see how the validator is defined. Thanks.

**Comment by JeremySkinner** [comment]
Hi, I need the code *for the validator itself*

**Comment by JeremySkinner** [comment]
And why are you invoking the constructor with reflection? You should be either be instantiating it directly or using a DI container.
