### ISSUE TITLE
Exception when validating 2nd level nested properties

### ISSUE THREAD

**Issue by marcin-chwedczuk-meow** [JeremySkinner/FluentValidation#851]
### How to reproduce

The following program compiled with VS 2017, .NET Core 1.1 and FluentValidation 7.6.104 reproduces my problem:

```csharp
using System;
using FluentValidation;

namespace fluent_validation_test
{
    class Program
    {
        static void Main(string[] args)
        { 
            var obj = new OutherDto { Inner = null };
            var errors = new OutherValidator().Validate(obj);
            foreach (var e in errors.Errors)
            {
                Console.WriteLine(e);
            }
        }
    }

    public class OutherValidator : AbstractValidator<OutherDto>
    {
        public OutherValidator()
        {
            CascadeMode = CascadeMode.StopOnFirstFailure;

            RuleFor(x => x.Inner)
                .NotNull();

            RuleFor(x => x.Inner.TestB)
                .NotNull();
        }
    }

    public class InnerDto
    {
        public bool? TestB { get; set; }
        public string TestS { get; set; }
    }

    public class OutherDto
    {
        public InnerDto Inner { get; set; }
    }
}
```

I get the following exception:
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=FluentValidation
  StackTrace:
   at FluentValidation.Internal.Extensions.<>c__DisplayClass9_0`2.<CoerceToNonGeneric>b__0(Object x) in C:\Projects\fluentvalidation\src\FluentValidation\Internal\Extensions.cs:line 154
   at FluentValidation.Validators.PropertyValidatorContext.<>c__DisplayClass24_0.<.ctor>b__0() in C:\Projects\fluentvalidation\src\FluentValidation\Validators\PropertyValidatorContext.cs:line 53
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at FluentValidation.Validators.NotNullValidator.IsValid(PropertyValidatorContext context) in C:\Projects\fluentvalidation\src\FluentValidation\Validators\NotNullValidator.cs:line 30
   at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context) in C:\Projects\fluentvalidation\src\FluentValidation\Validators\PropertyValidator.cs:line 79
   at FluentValidation.Internal.PropertyRule.<Validate>d__64.MoveNext() in C:\Projects\fluentvalidation\src\FluentValidation\Internal\PropertyRule.cs:line 267
   at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in C:\Projects\fluentvalidation\src\FluentValidation\AbstractValidator.cs:line 128
   at fluent_validation_test.Program.Main(String[] args) in c:\users\mchwedczuk\tmp\fluent-validation-test\fluent-validation-test\Program.cs:line 11
```

### Workaround

You must use `DependentRules` to wrap validation of inner properties.

```csharp
RuleFor(x => x.Inner)
                .NotNull()
                .DependentRules(() =>
                {
                    RuleFor(x => x.Inner.TestB)
                        .NotNull();
                });
```

Other workaround is to create a separate validator for Inner class.

### Expected behavior

This is not intuitive for me. I also cannot find relevant description in the documentation. Expected behavior IMHO would be to *ignore* all validation rules attached to property that has a `null` parent in its access chain.

**Comment by JeremySkinner** [comment]
Hi, thanks for the feeback. The usual way of handling this is with a When check: `RuleFor(x  => x.Inner.TestB).NotNull().When(x => x.Inner != null)`  (or a block When clause if you have multiple properties to check).

> Expected behavior IMHO would be to ignore all validation rules attached to property that has a null parent in its access chain.

If you set a child validator with `SetValidator` (which is the recommended way of handling child properties) then this is actually what  happens. The child validator will be skipped if the propert is null. However if you want to validate the child properties in the root level then you have to be explicit about whether you want them to run or not.

**Comment by JeremySkinner** [comment]
Docs updated; https://fluentvalidation.net/start#complex-properties
