### ISSUE TITLE
ShouldHaveValidationErrorFor throws NullReferenceException

### ISSUE THREAD

**Issue by fredemagi** [JeremySkinner/FluentValidation#953]
I'm trying to do some unit testing with ShouldHaveValidationErrorFor, but when I try to execute the test, it throws an NullReferenceException. 

The test looks like:

` [Test]
  public void NameIsNull_ExpectError()
  {
       validator.ShouldHaveValidationErrorFor(x => x.Name, "hej");
  }`

The constructor initializes the validator with a new instance of it. The validation rule looks like:

`RuleFor(x => x.Name).NotEmpty();`. 

Did I do something wrong? The guide at [fluentvalidation](https://fluentvalidation.net/testing) tells that this should be the correct syntax.

**Comment by JeremySkinner** [comment]
Can you provide a stack trace please.

**Comment by fredemagi** [comment]
> Test Name:	NameIsNull_ExpectError
Test FullName:	Gravplan.Tests.BusinessValidatorTest.NameIsNull_ExpectError
Test Source:	C:\Users\frederik.hornbak\source\repos\gravplan-docs\src\Gravplan.Tests\BusinessValidatorTest.cs : line 35
Test Outcome:	Failed
Test Duration:	0:00:00,214

Result StackTrace:	
at lambda_method(Closure , BusinessRequest )
   at FluentValidation.Internal.Extensions.<>c__DisplayClass9_0`2.<CoerceToNonGeneric>b__0(Object x) in C:\Projects\FluentValidation\src\FluentValidation\Internal\Extensions.cs:line 155
   at FluentValidation.Validators.PropertyValidatorContext.<>c__DisplayClass26_0.<.ctor>b__0() in C:\Projects\FluentValidation\src\FluentValidation\Validators\PropertyValidatorContext.cs:line 51
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at FluentValidation.Validators.NotEmptyValidator.IsValid(PropertyValidatorContext context) in C:\Projects\FluentValidation\src\FluentValidation\Validators\NotEmptyValidator.cs:line 32
   at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context) in C:\Projects\FluentValidation\src\FluentValidation\Validators\PropertyValidator.cs:line 51
   at FluentValidation.Internal.PropertyRule.InvokePropertyValidator(ValidationContext context, IPropertyValidator validator, String propertyName) in C:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 414
   at FluentValidation.Internal.PropertyRule.<Validate>d__64.MoveNext() in C:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 267
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in C:\Projects\FluentValidation\src\FluentValidation\AbstractValidator.cs:line 113
   at FluentValidation.AbstractValidator`1.FluentValidation.IValidator.Validate(ValidationContext context) in C:\Projects\FluentValidation\src\FluentValidation\AbstractValidator.cs:line 67
   at FluentValidation.DefaultValidatorExtensions.Validate[T](IValidator`1 validator, T instance, IValidatorSelector selector, String ruleSet) in C:\Projects\FluentValidation\src\FluentValidation\DefaultValidatorExtensions.cs:line 876
   at FluentValidation.TestHelper.ValidationTestExtension.TestValidate[T,TValue](IValidator`1 validator, Expression`1 expression, T instanceToValidate, TValue value, String ruleSet, Boolean setProperty) in C:\Projects\FluentValidation\src\FluentValidation\TestHelper\ValidatorTestExtensions.cs:line 102
   at FluentValidation.TestHelper.ValidationTestExtension.ShouldHaveValidationErrorFor[T,TValue](IValidator`1 validator, Expression`1 expression, TValue value, String ruleSet) in C:\Projects\FluentValidation\src\FluentValidation\TestHelper\ValidatorTestExtensions.cs:line 34
   at Gravplan.Tests.BusinessValidatorTest.NameIsNull_ExpectError() in C:\Users\frederik.hornbak\source\repos\gravplan-docs\src\Gravplan.Tests\BusinessValidatorTest.cs:line 37
Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.

**Comment by JeremySkinner** [comment]
Please can you post the full test code, the class definition and the validator definition.

**Comment by fredemagi** [comment]
Yes, of course:

**Test**

`[TestFixture]
 public class BusinessValidatorTest
 {
     private BusinessRequestValidator validator;

     [SetUp]
     public void Setup()
     {
         validator = new BusinessRequestValidator();
     }
     [Test]
     public void NameIsNull_ExpectError()
     {
         validator.ShouldHaveValidationErrorFor(x => x.Name, null as string);
     }
 }`

**Class definition**

` public class BusinessRequest
  {
      public string Name { get; set; }
  }`

**Validator**

` public class BusinessRequestValidator : AbstractValidator<BusinessRequest>
  {
      public BusinessRequestValidator()
      {
          //Object itself.
          RuleFor(x => x).NotNull();

          //Name.
          RuleFor(x => x.Name).NotEmpty();
      }
  }`

**Comment by JeremySkinner** [comment]
(Quick tip, [github uses triple backticks for code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/))

This worked fine for me...using that same code the test passed successfully without any errors on a fresh project (using latest version of FluentValidation 8.0.100)
